### PR TITLE
fix(pagination): should be optional

### LINKED ISSUE #105: crash if github releases don't paginate
Seems we require the link fields to exist, but they don't if you have less than a page of releases.

### PR DESCRIPTION
**Pull request by ashleygwilliams**
fixes #105  this code is gross but should do the trick

### CODE REVIEW

File: axoupdater/src/release/github.rs [hunk 1]
```diff
@@ -149,27 +149,43 @@ pub(crate) async fn get_github_releases(
...
         let resp = get_releases(&client, &url, token).await?;
 
+        // collect the response headers
         let headers = resp.headers();
-        let link_header = &headers[reqwest::header::LINK]
-            .to_str()
-            .expect("header was not ascii")
-            .to_string();
-        pages_remain = link_header.contains("rel=\"next\"");
+        let link_header_val = &headers[reqwest::header::LINK];
```
Comment (mistydemeo) [inline axoupdater/src/release/github.rs:157]: I think the issue here is that the index operation panics if the header isn't there: https://docs.rs/reqwest/0.12.4/reqwest/header/struct.HeaderMap.html#method.index

We should probably use `&headers.get(reqwest::header::LINK)`, which returns an `Option<T>` instead and lets us react properly: https://docs.rs/reqwest/0.12.4/reqwest/header/struct.HeaderMap.html#method.get

**Review by mistydemeo — CHANGES_REQUESTED** [review]

File: axoupdater/src/release/github.rs [hunk 2]
```diff
@@ -149,27 +149,39 @@ pub(crate) async fn get_github_releases(
...
 
+        // collect the response headers
         let headers = resp.headers();
-        let link_header = &headers[reqwest::header::LINK]
-            .to_str()
-            .expect("header was not ascii")
-            .to_string();
-        pages_remain = link_header.contains("rel=\"next\"");
+        let link_header_val = &headers.get(reqwest::header::LINK);
+        let link_header = link_header_val.as_ref().map(|link_header_val| {
```
Comment (mistydemeo) [inline axoupdater/src/release/github.rs:158]: Minor nit: we probably don't actually have to assign `link_header_val` above and could just chain this here (which'd make the reuse of the `link_header_val` variable name a little clearer)

**Review by mistydemeo — APPROVED** [review]

File: axoupdater/src/release/github.rs (hunk 2 above)
Comment (ashleygwilliams) [reply axoupdater/src/release/github.rs:158]: sure thing

**Review by mistydemeo — APPROVED** [review]
